name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: Fufuhu
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          VERSION=$(git rev --short)
          docker build -t fufuhu/bash_webserver:$VERSION .

      - name: Push Docker image
        run: |
          docker push fufuhu/bash_webserver:$VERSION
