name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fufuhu
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get image tag
        id: get-image-tag
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile
          tags: |
            fufuhu/bash_webserver:${{ steps.get-image-tag.outputs.tag }}
            fufuhu/bash_webserver:latest
